# Continuous Integration
#
# References:
#
# - https://docs.github.com/actions/learn-github-actions/contexts
# - https://docs.github.com/actions/learn-github-actions/expressions
# - https://docs.github.com/actions/using-jobs/using-a-matrix-for-your-jobs
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#push
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# - https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#push
# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
# - https://github.com/GitGuardian/ggshield-action
# - https://github.com/actions/cache
# - https://github.com/actions/cache/discussions/650
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node
# - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#yarn2-configuration
# - https://github.com/actions/upload-artifact
# - https://github.com/andstor/file-existence-action
# - https://github.com/codecov/codecov-action
# - https://github.com/codecov/test-results-action
# - https://github.com/dprint/check
# - https://github.com/flex-development/grease
# - https://github.com/hmarr/debug-action
# - https://github.com/streetsidesoftware/cspell-action
# - https://yarnpkg.com/cli/pack

---
name: ci
on:
  pull_request:
  push:
    branches:
      - feat/**
      - hotfix/**
      - main
  workflow_dispatch:
permissions:
  contents: read
env:
  CACHE_PATH: node_modules
  HUSKY: 0
  REF: ${{ github.head_ref || github.ref }}
  REF_NAME: ${{ github.head_ref || github.ref_name }}
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  preflight:
    if: |
      github.event_name == 'pull_request' ||
      github.event.head_commit.committer.username != 'web-flow'
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.result }}
      version: ${{ steps.build-version.outputs.result }}
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v3.0.0
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: dependencies
        name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: ${{ github.actor != 'dependabot[bot]' }}
        run: yarn
      - id: cache-key
        name: Get cache key
        run: echo "result=${{ hashFiles('yarn.lock') }}" >>$GITHUB_OUTPUT
      - id: cache
        name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          key: ${{ steps.cache-key.outputs.result }}
          path: ${{ env.CACHE_PATH }}
      - id: manifest-version
        name: Get manifest version
        run: echo "result=$(jq .version package.json -r)" >>$GITHUB_OUTPUT
      - id: build-version
        name: Get build version
        run: |
          echo "result=${{ startsWith(github.head_ref || github.ref_name, 'release/') && steps.manifest-version.outputs.result || format('{0}+{1}', steps.manifest-version.outputs.result, github.event.pull_request.head.sha || github.sha) }}" >>$GITHUB_OUTPUT
  gitguardian:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - id: scan
        name: Scan commits with ggshield
        uses: GitGuardian/ggshield-action@v1.43.0
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        with:
          args: --all-policies --format sarif --show-secrets --with-incident-details --verbose
  commitlint:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: lint
        name: Check commitlint status
        if: github.run_number != '1'
        run: yarn commitlint --from $SHA~${{ github.event.pull_request.commits || 1 }} --to $SHA
  format:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: version
        name: Get dprint version
        run: echo "result=$(jq .devDependencies.dprint package.json -r)" >>$GITHUB_OUTPUT
      - id: check
        name: Check formatting
        uses: dprint/check@v2.3
        with:
          args: --config-discovery=false --incremental=false --log-level=info
          config-path: .dprint.jsonc
          dprint-version: ${{ steps.version.outputs.result }}
  lint:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: remark
        name: Check markdown files
        run: yarn remark
      - id: lint
        name: Check eslint files
        run: yarn check:lint
  spelling:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: spelling
        name: Check spelling
        uses: streetsidesoftware/cspell-action@v7.2.0
        with:
          config: .cspell.json
          inline: error
          treat_flagged_words_as_errors: true
          verbose: true
  typescript:
    needs: preflight
    runs-on: ubuntu-latest
    env:
      VITEST_REPORT: ./.vitest-reports/typecheck.blob.json
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: print-version
        name: Print TypeScript version
        run: jq .devDependencies.typescript package.json -r
      - id: typecheck
        name: Run typecheck
        run: yarn typecheck
      - id: report
        name: Upload report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ format('typecheck-{0}.blob.json', env.SHA) }}
          path: ${{ env.VITEST_REPORT }}
  test:
    needs: preflight
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
    env:
      COVERAGE_SUMMARY: ./coverage/coverage-summary.json
      NODE_NO_WARNINGS: 1
      PCT: .total.branches.pct + .total.functions.pct + .total.lines.pct + .total.statements.pct
      VITEST_REPORT: ./.vitest-reports/test.blob.json
    steps:
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: test
        name: Run tests
        run: |
          yarn test:cov --coverage.thresholds.100=false \
          && echo "coverage=$(jq '${{ env.PCT }}' ${{ env.COVERAGE_SUMMARY }} -r)" >>$GITHUB_OUTPUT
      - id: pct
        name: Print coverage points
        run: echo ${{ steps.test.outputs.coverage }}
      - id: report
        name: Upload report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ format('test-node{0}-{1}.blob.json', matrix.node-version, env.SHA) }}
          path: ${{ env.VITEST_REPORT }}
      - id: coverage-summary
        name: Upload coverage summary
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ format('coverage-node{0}-{1}.json', matrix.node-version, env.SHA) }}
          path: ${{ env.COVERAGE_SUMMARY }}
      - id: codecov-coverage
        name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          env_vars: GITHUB_JOB,GITHUB_REF_TYPE
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: ${{ format('node{0}', matrix.node-version) }}
          name: ${{ format('node{0}-{1}', matrix.node-version, env.SHA) }}
          override_branch: ${{ env.REF }}
          override_build: ${{ github.run_id }}
          override_commit: ${{ env.SHA }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          working-directory: ${{ github.workspace }}
      - id: codecov-results
        if: ${{ !cancelled() }}
        name: Upload test results to Codecov
        uses: codecov/test-results-action@v1.1.1
        with:
          env_vars: GITHUB_JOB,GITHUB_REF_TYPE
          fail_ci_if_error: true
          files: ./__tests__/reports/junit.xml
          flags: ${{ format('node{0}', matrix.node-version) }}
          name: ${{ format('node{0}-{1}', matrix.node-version, env.SHA) }}
          override_branch: ${{ env.REF }}
          override_build: ${{ github.run_id }}
          override_commit: ${{ env.SHA }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          working-directory: ${{ github.workspace }}
      - id: coverage-failure
        if: steps.test.outputs.coverage != '400'
        name: Coverage threshold failure (${{ steps.test.outputs.coverage }})
        run: yarn test:cov:reports
  artifacts:
    needs:
      - commitlint
      - format
      - gitguardian
      - lint
      - preflight
      - spelling
      - test
      - typescript
    runs-on: ubuntu-latest
    steps:
      - id: tarball
        name: Get tarball path
        run: |
          echo "result=${{ format('@{0}-{1}-{2}.tgz', github.repository_owner, github.event.repository.name, needs.preflight.outputs.version) }}" >>$GITHUB_OUTPUT
      - id: checkout
        name: Checkout ${{ env.REF_NAME }}
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: node
        name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc
      - id: cache
        name: Restore dependencies cache
        uses: actions/cache@v4.2.4
        with:
          key: ${{ needs.preflight.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}
      - id: local-binaries
        name: Add local binaries to $PATH
        run: echo "$GITHUB_WORKSPACE/$CACHE_PATH/.bin" >> $GITHUB_PATH
      - id: changelog
        name: Changelog preview
        env:
          TZ: ${{ vars.TZ }}
        run: echo "$(grease changelog)" >>$GITHUB_STEP_SUMMARY
      - id: pack
        name: Pack project
        run: yarn pack -o ${{ steps.tarball.outputs.result }}
      - id: typecheck
        name: Run typecheck
        run: yarn check:types:build
      - id: attw
        name: Analyze types distribution
        run: attw ${{ steps.tarball.outputs.result }}
      - id: archive
        name: Archive production artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.tarball.outputs.result }}
          path: ${{ steps.tarball.outputs.result }}
